favicon_ico:
favicon_png:

simple_search: http://google.com/search

menu:
  Home: /
  Archives: /archives

widgets:
- search
- category
- tag
- twitter

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

follow_me:
  facebook:
  github:
  googleplus:
  linkedin:
  pinterest:
  twitter:

# addthis plugin has a performance issue, disable by default
addthis:
  enable:
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

google_analytics:
rss:

# Date Format
date_format:
  shorthand: MMM Do
