favicon_ico: 
favicon_png: 

simple_search: http://google.com/search

menu:
  About: /about
  Archives: /archives
  Works: /works

widgets: 
- search
- category
- tag
- twitter

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

follow_me:
  facebook:
  github: chrisyip
  googleplus:
  linkedin:
  pinterest:
  twitter: chrisyipw

# addthis plugin has a performance issue, disable by default
addthis:
  enable:
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: false

google_analytics:
rss: http://feeds.feedburner.com/imchrisyip

# Date Format
date_format:
  shorthand: MMM Do
