favicon_ico: 
favicon_png: 

simple_search: http://google.com/search

menu:
  About: /about
  Archives: /archives
  Works: /works

widgets: 
- search
- category
- tag
- twitter

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

follow_me:
  facebook:
  github: chrisyip
  googleplus:
  linkedin:
  pinterest:
  twitter: chrisyipw

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: false

google_analytics:
rss: atom.xml

# Linklog
linklog:
  permalink_label: "&infin;"
  permalink_label_feed: "&infin; Permalink"
  marker: "&rarr;"
  marker_position: before
  marker_position_feed: before
  standard_post_marker:

# Date Format
date_format:
  shorthand: MMM Do
