### Recommend to copy config to global _config.yml

favicon_ico:
favicon_png:

simple_search: http://google.com/search

menu:
  Home: /
  Archives: /archives

excerpt_link: Read More

follow_me:
  facebook:
  github:
  googleplus:
  linkedin:
  pinterest:
  twitter:

# addthis plugin has a performance issue, disable by default
addthis:
  enable:
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

google_analytics:
rss:

# Date Format
date_format:
  shorthand: MMM Do
